version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    image: ghcr.io/open-webui/open-webui:main
    restart: always
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - OLLAMA_BASE_URL="" # yerel aramayı kapatır
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
      
      # - ENABLE_SIGNUP=false 
    depends_on:
      - db
    volumes:
      - data:/app/backend/data

volumes:
  db-data:
  data: