model_list:
  - model_name: "claude-3-7-sonnet-thinking:1m"
    litellm_params:
      model: anthropic/claude-3-7-sonnet-20250219
      api_key: "os.environ/API_KEY"
      api_base: "https://api.yuxor.tech"
      max_tokens: 64000
      temperature: 1.0
      thinking: 
        type: "enabled"
        budget_tokens: 16000
      extra_headers:
        anthropic-beta: "output-128k-2025-02-19"

litellm_settings:
  drop_params: true
  modify_params: true