model_list:
  - model_name: "claude-opus-4-6-thinking:1m"
    litellm_params:
      model: anthropic/claude-opus-4-6
      api_key: "os.environ/API_KEY"
      api_base: "https://api.yuxor.tech" # Garanti olması için /v1 ekledim
      max_tokens: 64000 # KRİTİK: budget_tokens'tan (20000) büyük olmalı
      temperature: 1.0 # KRİTİK: Thinking için mecburi
      extra_headers:
        anthropic-beta: "output-128k-2025-02-19" # Eğer Yuxor 1m context için özel bir başlık istiyorsa virgülle buraya ekle (örn: "context-1m-2025-08-07, output-128k-2025-02-19")
      thinking: 
        type: "enabled"
        budget_tokens: 2048 # Must be less than max_tokens

litellm_settings:
  drop_params: true