services:
  nginx:
    image: nginx:1.29
    container_name: nginx-app
    restart: always
    ports:
      - "80:80"
    volumes:
        - ./default.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      - LOCAL_DOMAIN=${LOCAL_DOMAIN}
    networks:
      - proxy-agi

networks:
  proxy-agi:
    external: true
    name: nginx-main
