services:
  portainer:
    image: portainer/portainer-ce:2.38.1
    container_name: portainer-app
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - app-data:/data
    networks:
      - proxy-agi

volumes:
  app-data:
    name: portainer-app-data

networks:
  proxy-agi:
    external: true
    name: nginx-main