# VERITABANI

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

#test, performans ekstrasi saglamasi lazim
spring.jpa.open-in-view=false

# LOGGING

logging.level.org.springframework.security=DEBUG

# JWT

jwt-secret-key=${JWT_SECRET_KEY}

# HIBERNATE SEARCH (ELASTICSEARCH)

spring.jpa.properties.hibernate.search.backend.type=elasticsearch
spring.jpa.properties.hibernate.search.backend.uris=http://elastisearch-app:9200

#geliÅtirme aÅamasÄ±nda her uygulama kalktÄ±ÄÄ±nda indeks ÅemasÄ±nÄ± otomatik gÃ¼ncellesin
spring.jpa.properties.hibernate.search.backend.schema_management.strategy=drop-and-create

#mevcut veritabanÄ±ndaki kayÄ±tlarÄ± uygulama baÅlarken Elasticsearch'e aktar (Mass Indexing iÃ§in gerekli)
spring.jpa.properties.hibernate.search.automatic_indexing.synchronization.strategy=read-sync