services:
  db:
    image: postgres:18
    container_name: springproject-db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - internal

  app:
    image: ghcr.io/huseyun/kulakliksatisapi:master
    container_name: springproject-backend
    restart: always
    volumes:
      - ./application.properties:/app/application.properties
    environment:
      - DB_URL=jdbc:postgresql://db:5432/${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - db
    networks:
      - proxy-agi
      - internal

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: kulaklik-elasticsearch
    environment:
      - discovery.type=single-node # Cluster kurmuyoruz, tekil node olarak çalışacak
      - xpack.security.enabled=false # Lokal ortamda şifre/HTTPS ile uğraşmamak için güvenliği kapatıyoruz
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g" # Elasticsearch'e 1GB RAM ayırıyoruz
    ports:
      - "9200:9200" # Spring Boot'un bağlanacağı port
    volumes:
      - es_data:/usr/share/elasticsearch/data # Konteyner kapandığında indeksler silinmesin diye
    networks:
      - internal

networks:
  proxy-agi:
    external: true
    name: nginx-main
  internal:
    driver: bridge
